- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install PHP
  apt:
    name: php
    state: present
    update_cache: yes

- name: Enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes
